name: flutter_smartdio
description: A transport-agnostic HTTP wrapper that enhances ANY HTTP client with offline caching, request queuing, retry mechanisms, and comprehensive logging.
version: 1.0.3
homepage: https://github.com/rahulshahDEV/flutter_smartdio

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  dio: ^5.8.0
  http: ^1.4.0
  chopper: ^8.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12

# flutter: